# Generated by Django 4.1 on 2022-08-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_duration',
            field=models.DurationField(max_length=255),
        ),
    ]
