# Generated by Django 4.1 on 2022-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_movies_movie_time_alter_plays_play_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_language',
            field=models.CharField(default='Hindi', max_length=11),
        ),
        migrations.AddField(
            model_name='plays',
            name='play_language',
            field=models.CharField(default='Hindi', max_length=11),
        ),
    ]
