# Generated by Django 4.1 on 2022-08-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_movies_movie_language_plays_play_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='play_id',
        ),
    ]
