# Generated by Django 4.1 on 2022-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_movies_movie_id_remove_plays_play_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_language',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_duration',
            field=models.DurationField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_language',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='play_poster',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
