# Generated by Django 4.1 on 2022-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_movies_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plays',
            name='play_id',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
