# Generated by Django 4.1 on 2022-08-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_plays_play_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='play_id',
        ),
    ]
