# Generated by Django 4.1 on 2022-08-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_movies_show_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='show_type',
        ),
    ]
