# Generated by Django 4.1 on 2022-08-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='seat_nos',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
