# Generated by Django 4.1 on 2022-08-13 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='show_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='show_theatre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookings',
            name='show_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ticket_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
