# Generated by Django 4.1 on 2022-08-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookings_booked_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_id',
        ),
    ]
