# Generated by Django 4.1 on 2022-08-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookings_booked_at_alter_bookings_booked_show_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booked_show',
            new_name='show',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='show_theatre',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='ticket_quantity',
        ),
        migrations.AddField(
            model_name='bookings',
            name='seat_nos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
