# Generated by Django 4.0.4 on 2022-08-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
