# Generated by Django 4.1 on 2022-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seats_delete_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_number',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
